name: Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.github/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Deploy to Docker host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DOCKER_HOST }}
        username: ${{ secrets.DOCKER_USER }}
        key: ${{ secrets.DOCKER_SSH_KEY }}
        port: 22
        script: |
          cd ${{ secrets.DOCKER_APP_PATH }}
          git fetch origin main
          git reset --hard origin/main
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          docker system prune -f 